[package]
name = "pangu_native"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.20.0"
cli-clipboard = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate_type = ["cdylib"]
